DROP FUNCTION IF EXISTS NameUser;

DELIMITER $$

CREATE FUNCTION NameUser(iduser INT) RETURNS VARCHAR(30) DETERMINISTIC
BEGIN
	DECLARE reader VARCHAR(30) default "No user name with given id";
	IF iduser > 0 OR NOT NULL THEN
		SET reader = (SELECT CONCAT(FIRSTNAME,' ',LASTNAME) AS NAME FROM readers WHERE READER_ID = iduser);
	END IF;
    RETURN reader;
END $$

DELIMITER ;

SELECT NameUser(7) AS NAME;

//ERROR: (OPERAND SHOULD CONTAIN 1 COLUMN)//