DROP TABLE IF EXISTS BOOKS_AUD;

CREATE TABLE BOOKS_AUD (
  EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
  EVENT_DATE DATETIME NOT NULL,
  EVENT_TYPE VARCHAR(50) DEFAULT NULL,
  BOOK_ID int(11) NOT NULL,
  OLD_TITLE VARCHAR(50) DEFAULT NULL,
  NEW_TITLE VARCHAR(50) DEFAULT NULL,
  OLD_PUBYEAR INT(4) DEFAULT NULL,
  NEW_PUBYEAR INT(4) DEFAULT NULL,
  OLD_BESTSELLERS TINYINT(4),
  NEW_BESTSELLERS TINYINT(4),
  PRIMARY KEY (EVENT_ID)
);


DROP TRIGGER IF EXISTS BOOKS_INSERT;

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN

	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLERS)
    VALUES (CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLERS);
END $$

DELIMITER ;


DROP TRIGGER IF EXISTS BOOKS_DELETE;

DELIMITER $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN

	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
    VALUES (CURTIME(), "DELETE", OLD.BOOK_ID);
END $$

DELIMITER ;


DROP TRIGGER IF EXISTS BOOKS_UPDATE;

DELIMITER $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN

	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLERS,
							OLD_TITLE, OLD_PUBYEAR, OLD_BESTSELLERS)
    VALUES (CURTIME(), "UPDATE", OLD.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLERS,
			 OLD.TITLE, OLD.PUBYEAR, OLD.BESTSELLERS);
END $$

DELIMITER ;