DROP VIEW IF EXISTS BESTSELLERS_COUNT;

CREATE VIEW BESTSELLERS_COUNT AS

SELECT COUNT(BESTSELLERS) AS NMR_OF_BESTSELLERS FROM BOOKS;


CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);


DROP EVENT IF EXISTS UPDATE_BESTSELLERS;

USE KODILLA_COURSE;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS

ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
CALL UpdateBestsellers();
INSERT INTO STATS
SET STAT = "BESTSELLERS", STAT_DATE = curdate(),
VALUE = (SELECT NMR_OF_BESTSELLERS FROM BESTSELLERS_COUNT);

END $$

DELIMITER ;

COMMIT;

SELECT * FROM STATS;