DROP VIEW IF EXISTS BESTSELLERS_COUNT;

CREATE VIEW BESTSELLERS_COUNT AS

SELECT COUNT(BESTSELLERS) AS NMR_OF_BESTSELLERS FROM BOOKS;


CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);


USE KODILLA_COURSE;

CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO CALL UpdateBestsellers();


UPDATE STATS
SET VALUE = (SELECT NMR_OF_BESTSELLERS FROM BESTSELLERS_COUNT);

COMMIT;

SELECT * FROM STATS;